"""add_reset_token_to_user

Revision ID: 24aa25f64fd3
Revises: 71fab63afc86
Create Date: 2026-07-09 11:20:39.766721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24aa25f64fd3'
down_revision = '71fab63afc86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('token_reinitialisation', sa.String(length=256), nullable=True))
    op.add_column('utilisateurs', sa.Column('expire_token_reinitialisation', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'expire_token_reinitialisation')
    op.drop_column('utilisateurs', 'token_reinitialisation')
    # ### end Alembic commands ###
