"""add status and attempts to message logs

Revision ID: 4425b57b26c1
Revises: 476501b1c521
Create Date: 2026-06-11 22:55:03.820865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4425b57b26c1'
down_revision = '476501b1c521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_logs', sa.Column('status', sa.String(length=32), nullable=False, server_default=sa.text("'sent'")))
    op.add_column('message_logs', sa.Column('attempts', sa.Integer(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_logs', 'attempts')
    op.drop_column('message_logs', 'status')
    # ### end Alembic commands ###
