"""add appointment reminder and user phone

Revision ID: 476501b1c521
Revises: 4d2845d49e9c
Create Date: 2026-06-11 22:38:35.575821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476501b1c521'
down_revision = '4d2845d49e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reminder_sent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('utilisateurs', sa.Column('phone_number', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'phone_number')
    op.drop_column('appointments', 'reminder_sent')
    # ### end Alembic commands ###
