"""add secondary phone to patient

Revision ID: 4d2845d49e9c
Revises: cc27fe96ce66
Create Date: 2026-06-11 21:56:37.115872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2845d49e9c'
down_revision = 'cc27fe96ce66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('secondary_phone_number', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'secondary_phone_number')
    # ### end Alembic commands ###
