"""add_email_to_user

Revision ID: 71fab63afc86
Revises: 4425b57b26c1
Create Date: 2026-07-09 11:06:26.633015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fab63afc86'
down_revision = '4425b57b26c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'email')
    # ### end Alembic commands ###
